on:
  push:
    branches-ignore:
      - 'main'

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Build Affected
        run: npx nx affected --target=build --parallel --max-parallel=3
      - name: Lint Affected
        run: npx nx affected --target=lint --parallel --max-parallel=2
      - name: Unit-Tests Affected
        run: npx nx affected --target=test --parallel --max-parallel=2
      - name: E2E-Tests Affected
        run: npx nx affected --target=e2e --parallel --max-parallel=2
